ARG NODE_IMAGE=node:22-alpine
ARG NGINX_IMAGE=nginx:stable-alpine

FROM ${NODE_IMAGE} AS builder

WORKDIR /app

ARG NPM_REGISTRY=https://registry.npmmirror.com
ENV NPM_CONFIG_REGISTRY=${NPM_REGISTRY}
ENV npm_config_registry=${NPM_REGISTRY}
ENV COREPACK_NPM_REGISTRY=${NPM_REGISTRY}

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm config set registry "${NPM_REGISTRY}" && pnpm install --frozen-lockfile

COPY . .

ARG VITE_API_BASE=
ARG VITE_USE_MOCK=false
ARG VITE_RANK_VIDEO_MOCK=true
ARG VITE_RANK_WEIBO_MOCK=false
ARG VITE_OPENMAIC_BASE_URL=/openmaic
ARG VITE_OPENMAIC_APP_URL=
ARG VITE_OPENMAIC_PORT=3000
ARG VITE_EDUREPO_VIEW_MODE=native
ARG VITE_EDUREPO_APP_URL=
ARG VITE_MONITOR_APP_URL=
ARG VITE_ANDROID_APK_URL=/downloads/lingjing-android-latest.apk

ENV VITE_API_BASE=${VITE_API_BASE}
ENV VITE_USE_MOCK=${VITE_USE_MOCK}
ENV VITE_RANK_VIDEO_MOCK=${VITE_RANK_VIDEO_MOCK}
ENV VITE_RANK_WEIBO_MOCK=${VITE_RANK_WEIBO_MOCK}
ENV VITE_OPENMAIC_BASE_URL=${VITE_OPENMAIC_BASE_URL}
ENV VITE_OPENMAIC_APP_URL=${VITE_OPENMAIC_APP_URL}
ENV VITE_OPENMAIC_PORT=${VITE_OPENMAIC_PORT}
ENV VITE_EDUREPO_VIEW_MODE=${VITE_EDUREPO_VIEW_MODE}
ENV VITE_EDUREPO_APP_URL=${VITE_EDUREPO_APP_URL}
ENV VITE_MONITOR_APP_URL=${VITE_MONITOR_APP_URL}
ENV VITE_ANDROID_APK_URL=${VITE_ANDROID_APK_URL}

RUN pnpm build

FROM ${NGINX_IMAGE} AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
